development:
  secret_key_base: 3dc08c25a0bf8aecac9f3e096276bd676f9853dbc82a783ed509bf8045f0e80bfe354d3124cf153254a1fb36094d1a39daa30141d1f6fbd666be9fbd7da07afe
  pusher_key:
  pusher_cluster:
  domain_name: 0.0.0.0:3000
  aws_access_key_id: AKIAI3LWFZCWZVMVTRPQ
  aws_secret_access_key: 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
  aws_bucket: beautyapp-development

test:
  secret_key_base: 3005c66a468974c7f53929bd837903d7426f9c933e8f09d0042e4055083ed28ae09508eb680f6cf22c2002cba044df4a2b7aaca5f0e12bbf7c1badbdc8a9ccf0

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  domain_name: beautyapp.herokuapp.com
  aws_access_key_id: <%= ENV["AWS_ACCESS_KEY_ID"] %>
  aws_secret_access_key: <%= ENV["AWS_SECRET_ACCESS_KEY"] %>
  aws_bucket: <%= ENV["AWS_BUCKET"] %>
